console.log("Max's Collatz")


function collatz(num) {
	var list =[num]
	while (num > 1) {
		if (num % 2 == 0) {
			num = num/2;
		} else {
			num = 3*num + 1;
		}
		list.push(num);
		}
	return [list.length, list];
	}

if (typeof process.argv[2] === "undefined") {
	console.log("you didn't specify a number!");
}
else {
	var input = process.argv[2];
	var lists = collatz(input);
	console.log(lists[1] + "\n" 
	+ "the length of the sequence generated by " + input + " is " +  lists[0]);
}


